accounts:
  - captainhoff
  - daniallqureshi
  - youraveragetechbro
  - skip_ci
  - sicknider_raw
  - mattmurphy
  - umacodes
  - qendresahhoti
  - haydenschmitty
  - rollins_io
  - chase_h_ai
  - khashayartalks
  - jam_with_ai

per_account_limit: 5
prefer_reels: true